name: torrenium
description: Torrent Downloader

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  macos_ui: ^2.0.0
  cached_network_image: ^3.2.2
  http: ^1.1.0
  xml: ^6.1.0
  flutter_html: ^3.0.0-beta.2
  path_provider: ^2.0.11
  path: ^1.8.2
  logger: ^1.1.0
  flutter_cache_manager: ^3.3.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_offline: ^3.0.0
  connectivity_plus: ^4.0.2
  intl: ^0.18.1
  cupertino_icons: ^1.0.5
  media_kit: ^1.1.5
  media_kit_video: ^1.1.6
  media_kit_native_event_loop: ^1.0.7            # Support for higher number of concurrent instances & better performance.
  media_kit_libs_android_video: ^1.3.2           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.1.3               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.1.3             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.7           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.1.1                   # GNU/Linux dependency package.
  youtube_explode_dart: ^2.0.2
  ffi: ^2.1.0
  flutter_slidable: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  settings_ui: ^2.0.2
  flutter_animate: ^4.2.0+1
  get: ^4.6.5
  get_storage: ^2.1.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  ffigen: ^8.0.2
flutter:
  uses-material-design: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256