platform :ios, '11.0'

target 'Runner' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
  
    # Pods for Runner
    # Add your Flutter pods here
    # pod 'Flutter', :path => '../flutter'
  
    # Add the following line to link the .a library
    pod 'libtorrent_go_ios', :path => '../go_torrent/build/ios'
  
    # Add any other dependencies you may have
  
  end
  
  # Add more targets if you have them
  
  